export enum Description {
  USD = 'DOLAR',
  TPRV = 'TÍTULO DE PARTICIPACIÓN RENTA VARIABLE',
  TP = 'TÍTULO DE PARTICIPACIÓN',
  TID = 'TIDIS',
  THI = 'TITULOS HIPOTECARIOS',
  TESU = 'TES UVR',
  TEST = 'TEST TRM',
  TESP = 'TES PESOS',
  TESOROS = 'BONOS DEL TESORO EEUU',
  TESI = 'TES IPC',
}
